# Generated by Django 4.1.3 on 2022-12-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currentBalance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateField(auto_now=True, null=True)),
                ('transactionAmount', models.FloatField()),
                ('customerById', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerBy', to='main.customer')),
                ('customerToId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerTo', to='main.customer')),
            ],
        ),
    ]
